# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aligner_pb2 as aligner__pb2


class WordAlignerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AlignWords = channel.unary_unary(
                '/aligner.WordAligner/AlignWords',
                request_serializer=aligner__pb2.SentencesRequest.SerializeToString,
                response_deserializer=aligner__pb2.AlignmentReply.FromString,
                )


class WordAlignerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AlignWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordAlignerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AlignWords': grpc.unary_unary_rpc_method_handler(
                    servicer.AlignWords,
                    request_deserializer=aligner__pb2.SentencesRequest.FromString,
                    response_serializer=aligner__pb2.AlignmentReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aligner.WordAligner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WordAligner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AlignWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aligner.WordAligner/AlignWords',
            aligner__pb2.SentencesRequest.SerializeToString,
            aligner__pb2.AlignmentReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
