version: '3.7'

volumes:
    postgres2:
    certs:
      driver: local
    esdata01:
      driver: local
    kibanadata:
      driver: local
    postgres1:
    frontend:

networks:
  backend-network:
    driver: "bridge"
  default:
    name: elastic
    external: false

services:
  postgres-1:
    container_name: postgres-1
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_DB: parcorpusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: postgres
      POSTGRESQL_REPLICATION_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: parcorpusdb
    volumes:
      - 'postgres1:/bitnami/postgresql'
      - './Parcorpus/scripts/roles.sql:/docker-entrypoint-initdb.d/roles.sql'
    ports:
      - "5434:5432"
    networks:
      - backend-network
  
  postgres-2:
    container_name: postgres-2
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_DB: parcorpusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: postgres
      POSTGRESQL_REPLICATION_PASSWORD: postgres
      POSTGRESQL_MASTER_HOST: postgres-1
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
    volumes:
      - 'postgres2:/bitnami/postgresql'
      - './Parcorpus/scripts/roles.sql:/docker-entrypoint-initdb.d/roles.sql'
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - backend-network
    depends_on:
      - postgres-1
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend-network
  
  backend-main:
    container_name: parcorpus-backend
    build: './Parcorpus/'
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=${DB_CONNECTION_STRING}
      - WordAlignerConfiguration__WordAlignerServer=${WORD_ALIGNER}
      - ELASTIC_URL=${ELASTIC_URL}
      - QueueConfiguration__ConnectionString=${RABBITMQ_CONNECTION_STRING}
    volumes:
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/appsettings.json:/app/appsettings.json'
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/NLog.config:/app/NLog.config'
      - './Parcorpus/src/Parcorpus.API/logs:/app/log'
    depends_on:
      - postgres-1
      - aligner
      - rabbitmq
    networks:
      - backend-network
    ports:
      - 446:443
      - 802:80

  backend-read-only-1:
    build: './Parcorpus/'
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=${DB_CONNECTION_STRING}
      - WordAlignerConfiguration__WordAlignerServer=${WORD_ALIGNER}
      - ELASTIC_URL=${ELASTIC_URL}
      - QueueConfiguration__ConnectionString=${RABBITMQ_CONNECTION_STRING}
    volumes:
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/appsettings.json:/app/appsettings.json'
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/NLog.config:/app/NLog.config'
      - './Parcorpus/src/Parcorpus.API/logs:/app/log'
    depends_on:
      - postgres-1
      - aligner
      - rabbitmq
      - backend-main
    networks:
      - backend-network
    ports:
      - 447:443
      - 803:80
  
  backend-read-only-2:
    build: './Parcorpus/'
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=${DB_CONNECTION_STRING}
      - WordAlignerConfiguration__WordAlignerServer=${WORD_ALIGNER}
      - ELASTIC_URL=${ELASTIC_URL}
      - QueueConfiguration__ConnectionString=${RABBITMQ_CONNECTION_STRING}
    volumes:
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/appsettings.json:/app/appsettings.json'
      - './Parcorpus/src/Parcorpus.API/Parcorpus.API/NLog.config:/app/NLog.config'
      - './Parcorpus/src/Parcorpus.API/logs:/app/log'
    depends_on:
      - postgres-1
      - aligner
      - rabbitmq
      - backend-main
    networks:
      - backend-network
    ports:
      - 448:443
      - 804:80
  
  aligner:
    build: ./Parcorpus/src/Parcorpus.Services/Parcorpus.Services.AnnotationService/WordAlignerServer
    volumes:
        - ./Parcorpus/src/Parcorpus.Services/Parcorpus.Services.AnnotationService/WordAlignerServer:/usr/app/
    networks:
      - backend-network
    ports:
      - 50051:50051
  
  nginx:
    image: byjg/nginx-extras
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./docs:/docs
    working_dir: /parcorpus
    ports:
      - "80:80"
      - "443:443"
    restart:
      always
    depends_on:
      - backend-main
    networks:
      - backend-network
  
  # frontend:
  #   container_name: frontend
  #   image: parcorpus-frontend:1.0
  #   depends_on:
  #     - backend-main
  #   volumes:
  #     - 'frontend:/app'
  #   ports:
  #     - '5173:5173'
  #   networks:
  #     - backend-network